version: '3.7'
services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/default.conf
    networks:
      - puzzle
  front:
    container_name: front
    image: puzzle_node_env
    environment:
      - ENV=development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    tty: true
    ports:
      - 8080:8080
    networks:
      - puzzle
    
networks:
  puzzle:
    driver: bridge